import type { Alert } from '../types'

export const mockAlerts: readonly Alert[] = [
  {
    id: 'alert-001',
    user_id: 'user-mock-001',
    trend_id: 'trend-001',
    alert_type: 'Breakout',
    title: 'AI Agents - Breakout Signal Detected',
    message: 'AI Agents crossed score 85. HackerNews velocity is up 42% this week. GitHub stars accelerating. This may be a short window before competition intensifies.',
    sent_at: '2025-06-15T08:00:00Z',
  },
  {
    id: 'alert-002',
    user_id: 'user-mock-001',
    trend_id: 'trend-036',
    alert_type: 'Breakout',
    title: 'AI-Optimized GPU Clouds - Peak Warning',
    message: 'GPU Cloud trend score hit 83 but confidence indicates peak is within 2 months. Hyperscaler capacity additions are flooding the market. Consider timing carefully.',
    sent_at: '2025-06-15T08:05:00Z',
  },
  {
    id: 'alert-003',
    user_id: 'user-mock-001',
    trend_id: 'trend-032',
    alert_type: 'Decay',
    title: 'Web3 Gaming - Continued Decline',
    message: 'Web3 Gaming velocity is -8 points on Reddit, -6 on Google Trends. Play-to-earn user counts down 78% from 2022 peak. Category is structurally declining.',
    sent_at: '2025-06-14T09:00:00Z',
  },
  {
    id: 'alert-004',
    user_id: 'user-mock-001',
    trend_id: 'trend-030',
    alert_type: 'Decay',
    title: 'D2C Subscription Boxes - Structural Decline',
    message: 'Subscription box cancellation rates hit 44% annually. New launches down 60% from 2021 peak. The model is economically challenged at current shipping costs.',
    sent_at: '2025-06-14T09:10:00Z',
  },
  {
    id: 'alert-005',
    user_id: 'user-mock-001',
    watchlist_id: 'watchlist-001',
    trend_id: 'trend-004',
    alert_type: 'Breakout',
    title: 'AI Video Generation - Rapid Acceleration',
    message: 'AI Video Gen crossed into Accelerating stage. ProductHunt score up 22 points, funding announcements at $2.4B YTD. Window for vertical tools is open for 12-18 months.',
    sent_at: '2025-06-14T10:00:00Z',
    read_at: '2025-06-14T11:30:00Z',
  },
  {
    id: 'alert-006',
    user_id: 'user-mock-001',
    trend_id: 'trend-040',
    alert_type: 'Breakout',
    title: 'Vertical SaaS - Still in Build Window',
    message: 'Vertical SaaS remains at score 77 with Medium competition. Several unsexy industries (pest control, funeral services, marina) have near-zero digital penetration. Premium M&A multiples confirm demand.',
    sent_at: '2025-06-13T08:00:00Z',
    read_at: '2025-06-13T09:00:00Z',
  },
  {
    id: 'alert-007',
    user_id: 'user-mock-001',
    watchlist_id: 'watchlist-002',
    trend_id: 'trend-025',
    alert_type: 'Breakout',
    title: 'AI Observability Tools - Green Field Detected',
    message: 'AI Observability install growth hit 420% YoY with Low competition density. Every company building with LLMs needs this. Classic picks-and-shovels opportunity.',
    sent_at: '2025-06-13T09:00:00Z',
  },
  {
    id: 'alert-008',
    user_id: 'user-mock-001',
    trend_id: 'trend-039',
    alert_type: 'DailyDigest',
    title: 'Daily Digest - Enterprise AI segment update',
    message: 'Enterprise AI Copilots gained 3 points this week. 180 new ROI studies published this quarter. Microsoft Copilot enterprise contracts up 45%. Vertical-specific copilots capturing 3x the deal size of horizontal tools.',
    sent_at: '2025-06-12T07:00:00Z',
    read_at: '2025-06-12T08:00:00Z',
  },
  {
    id: 'alert-009',
    user_id: 'user-mock-001',
    trend_id: 'trend-034',
    alert_type: 'Breakout',
    title: 'Tokenized Real-World Assets - Emerging Signal',
    message: 'Tokenized RWA value hit $14B, up from $2B in 2023. SEC guidance clarity creating regulatory tailwind. BlackRock and Franklin Templeton entries validate the category. Infrastructure plays are highest opportunity.',
    sent_at: '2025-06-11T10:00:00Z',
  },
  {
    id: 'alert-010',
    user_id: 'user-mock-001',
    watchlist_id: 'watchlist-003',
    trend_id: 'trend-016',
    alert_type: 'DailyDigest',
    title: 'EdTech AI Digest - Tutoring breakthrough signal',
    message: 'AI Tutoring Systems showed 2.1 sigma learning improvement in new study. 400+ K-12 districts enrolled in pilots. Consumer direct-to-student revenue up 220% YoY. Build window 18-24 months.',
    sent_at: '2025-06-11T07:00:00Z',
    read_at: '2025-06-11T08:30:00Z',
  },
  {
    id: 'alert-011',
    user_id: 'user-mock-001',
    trend_id: 'trend-006',
    alert_type: 'Decay',
    title: 'AI Code Generation - Peak Signals',
    message: 'AI Code Gen is showing peak indicators: 62% developer penetration, new entrant funding down 40%, ARPU declining 8% QoQ. The IDE layer is being commoditized. The next cycle is autonomous dev agents.',
    sent_at: '2025-06-10T09:00:00Z',
    read_at: '2025-06-10T11:00:00Z',
  },
  {
    id: 'alert-012',
    user_id: 'user-mock-001',
    trend_id: 'trend-035',
    alert_type: 'DailyDigest',
    title: 'Infrastructure Digest - Edge compute accelerating',
    message: 'Edge Computing Platforms: invocations up 320% YoY, enterprise contracts up 145%. P95 latency down from 68ms to 12ms. CDN-to-edge compute migration underway at major platforms.',
    sent_at: '2025-06-10T07:00:00Z',
  },
  {
    id: 'alert-013',
    user_id: 'user-mock-001',
    watchlist_id: 'watchlist-001',
    trend_id: 'trend-003',
    alert_type: 'Breakout',
    title: 'Synthetic Data Generation - Early Mover Window',
    message: 'Synthetic Data paper count up 210% YoY. 12 enterprise case studies published. Healthcare and autonomous vehicles leading adoption. Low competition, 30-day build time, Emerging monetization. Classic early-mover opportunity.',
    sent_at: '2025-06-09T10:00:00Z',
  },
]
