import type { TrendAnalysis } from '../types'

export const mockAnalysis: readonly TrendAnalysis[] = [
  {
    id: 'analysis-001',
    trend_id: 'trend-001',
    analysis_stage: 'Accelerating',
    confidence_percent: 91,
    historical_pattern: 'Mirrors the DevOps tooling curve 2015-2017. Initial GitHub activity spike followed by rapid enterprise adoption.',
    ai_notes: 'Agent frameworks are consolidating around a few dominant primitives (tool use, memory, planning). The market leader position is not yet decided. Build windows are 6-12 months before commoditization.',
    key_indicators: [
      { indicator: 'GitHub stars growth (30d)', value: '+42%' },
      { indicator: 'HN front page mentions', value: '34 posts this month' },
      { indicator: 'Job postings with "AI agent"', value: '+280% YoY' },
      { indicator: 'VC deals tagged AI Agents', value: '18 in Q1 2025' },
    ],
    estimated_peak_months: 14,
    related_trends: ['trend-006', 'trend-007', 'trend-025'],
    updated_at: '2025-06-15T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-002',
    trend_id: 'trend-002',
    analysis_stage: 'Accelerating',
    confidence_percent: 83,
    historical_pattern: 'Follows the cloud database curve: commodity offering erodes margins but expands TAM significantly.',
    ai_notes: 'Fine-tuning is transitioning from research to production. The key differentiator is data flywheel -- platforms that help customers collect and label training data will compound advantages.',
    key_indicators: [
      { indicator: 'API calls to fine-tune endpoints', value: '+120% QoQ' },
      { indicator: 'Hugging Face model uploads', value: '+85% YoY' },
      { indicator: 'Average fine-tune cost', value: '-60% vs 12mo ago' },
    ],
    estimated_peak_months: 18,
    related_trends: ['trend-001', 'trend-003'],
    updated_at: '2025-06-10T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-003',
    trend_id: 'trend-003',
    analysis_stage: 'Emerging',
    confidence_percent: 67,
    historical_pattern: 'Early-stage signal, analogous to data labeling tools in 2017 before the MLOps wave.',
    ai_notes: 'Synthetic data adoption is gated by trust. Most enterprises are skeptical of training on generated data. The unlock will be rigorous benchmarks showing parity. First-movers in healthcare and autonomous vehicles have strongest signal.',
    key_indicators: [
      { indicator: 'Academic papers on synthetic training', value: '+210% YoY' },
      { indicator: 'Enterprise pilots announced', value: '12 public case studies' },
    ],
    estimated_peak_months: 30,
    related_trends: ['trend-002', 'trend-006'],
    updated_at: '2025-06-12T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-004',
    trend_id: 'trend-004',
    analysis_stage: 'Accelerating',
    confidence_percent: 88,
    historical_pattern: 'Matches text-to-image trajectory in 2022 but on a compressed timeline due to infrastructure improvements.',
    ai_notes: 'Video generation is 12-18 months behind image generation in productization. The winning playbook will be vertical niches (ad creative, social content, training simulations) rather than general-purpose video. Compute cost remains the primary moat.',
    key_indicators: [
      { indicator: 'Gen AI video startup funding', value: '$2.4B in 2025 YTD' },
      { indicator: 'User video outputs per month', value: '1.2B across top platforms' },
      { indicator: 'Enterprise contracts announced', value: '28 Fortune 500 deals' },
    ],
    estimated_peak_months: 16,
    related_trends: ['trend-001', 'trend-019', 'trend-022'],
    updated_at: '2025-06-14T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-005',
    trend_id: 'trend-005',
    analysis_stage: 'Emerging',
    confidence_percent: 72,
    historical_pattern: 'Pre-adoption curve similar to serverless functions in 2016 before Lambda popularized the category.',
    ai_notes: 'Edge inference is constrained by hardware. The consumer device upgrade cycle will be the primary demand driver. Watch Qualcomm and Apple chip announcements as leading indicators.',
    key_indicators: [
      { indicator: 'On-device ML framework downloads', value: '+180% YoY' },
      { indicator: 'Mobile AI chip announcements', value: '6 major OEMs in 2025' },
    ],
    estimated_peak_months: 36,
    related_trends: ['trend-035', 'trend-006'],
    updated_at: '2025-06-11T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-006',
    trend_id: 'trend-006',
    analysis_stage: 'Peaking',
    confidence_percent: 94,
    historical_pattern: 'Classic S-curve peak: rapid adoption has occurred, differentiation is narrowing, price competition intensifying.',
    ai_notes: 'The AI code generation market is near saturation at the IDE layer. The next wave is full autonomous dev agents (headless, PR-generating). Current tools will be commoditized into IDEs natively within 24 months.',
    key_indicators: [
      { indicator: 'Copilot-style tool market penetration', value: '62% of developers' },
      { indicator: 'New entrant funding (2025)', value: '-40% vs 2024' },
      { indicator: 'Average revenue per user', value: 'Declining 8% QoQ' },
    ],
    estimated_peak_months: 3,
    related_trends: ['trend-001', 'trend-025'],
    updated_at: '2025-06-15T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-007',
    trend_id: 'trend-007',
    analysis_stage: 'Emerging',
    confidence_percent: 76,
    historical_pattern: 'Early signal. Comparable to the early API economy before REST was standardized.',
    ai_notes: 'Multimodal apps are technically feasible but product-market fit is still being discovered. The biggest opportunities are use cases where multiple modalities are necessary (medical imaging + clinical notes, industrial inspection, etc.).',
    key_indicators: [
      { indicator: 'Multimodal API endpoint traffic', value: '+340% YoY' },
      { indicator: 'Products using 3+ modalities', value: '87 tracked apps' },
    ],
    estimated_peak_months: 24,
    related_trends: ['trend-001', 'trend-004', 'trend-006'],
    updated_at: '2025-06-13T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-008',
    trend_id: 'trend-008',
    analysis_stage: 'Accelerating',
    confidence_percent: 85,
    historical_pattern: 'Matches API economy expansion. Stripe for X playbook now proven across multiple verticals.',
    ai_notes: 'Embedded finance is being adopted fastest in SMB software (accounting, payroll, scheduling). The risk is regulatory -- BaaS sponsors facing increased OCC scrutiny may slow rollouts.',
    key_indicators: [
      { indicator: 'Embedded finance API integrations', value: '+156% YoY' },
      { indicator: 'Vertical SaaS with finance features', value: '38% of new products' },
      { indicator: 'BaaS sponsor bank approvals', value: '14 new entrants 2025' },
    ],
    estimated_peak_months: 20,
    related_trends: ['trend-011', 'trend-040'],
    updated_at: '2025-06-10T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-009',
    trend_id: 'trend-009',
    analysis_stage: 'Emerging',
    confidence_percent: 64,
    historical_pattern: 'Very early. Regulatory uncertainty is a significant headwind unlike most software categories.',
    ai_notes: 'Alternative credit scoring has been attempted multiple times and repeatedly blocked by regulatory pushback. Current cycle has better AI explainability tools which may address fair lending concerns. Still high-risk.',
    key_indicators: [
      { indicator: 'Pilot programs with lenders', value: '22 disclosed' },
      { indicator: 'Regulatory guidance issued', value: '3 positive CFPB signals' },
    ],
    estimated_peak_months: 40,
    related_trends: ['trend-008', 'trend-011'],
    updated_at: '2025-06-08T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-010',
    trend_id: 'trend-010',
    analysis_stage: 'Saturating',
    confidence_percent: 88,
    historical_pattern: 'Post-peak saturation. ACH modernization debates have been ongoing for 15 years. RTP rails now deployed but adoption plateauing.',
    ai_notes: 'Real-time payments infrastructure is largely built. The remaining opportunity is in the application layer -- instant payroll, earned wage access, and B2B payment orchestration. The plumbing is done; the differentiated value is UX.',
    key_indicators: [
      { indicator: 'RTP transaction volume growth', value: '+22% QoQ (slowing)' },
      { indicator: 'New entrant funding', value: '-65% from 2023 peak' },
      { indicator: 'Bank adoption rate', value: '94% of US banks on RTP' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-008', 'trend-011'],
    updated_at: '2025-06-05T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-011',
    trend_id: 'trend-011',
    analysis_stage: 'Peaking',
    confidence_percent: 80,
    historical_pattern: 'Neobank wave peaked 2021-2022 for consumer. B2B/vertical iteration is 2-3 years behind.',
    ai_notes: 'Vertical neobanks targeting professionals (doctors, truckers, gig workers) still have runway. The consumer generalist neobank market is oversaturated. Key signal: LTV/CAC on professional-focused products is 3-4x general consumer.',
    key_indicators: [
      { indicator: 'Professional niche neobank launches', value: '14 in 2025 YTD' },
      { indicator: 'Average NPS vs traditional banks', value: '+42 points' },
      { indicator: 'Gross margin on interchange', value: '68% average' },
    ],
    estimated_peak_months: 8,
    related_trends: ['trend-008', 'trend-040'],
    updated_at: '2025-06-12T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-012',
    trend_id: 'trend-012',
    analysis_stage: 'Accelerating',
    confidence_percent: 79,
    historical_pattern: 'Mirrors EHR adoption curve -- initial FDA clearance creates a cascade of vendor approvals.',
    ai_notes: 'Radiology AI has achieved clinical validation. Pathology and cardiology are 18-24 months behind. The bottleneck is now reimbursement coding, not FDA clearance. Target companies solving the billing problem alongside the clinical problem.',
    key_indicators: [
      { indicator: 'FDA 510(k) clearances for AI diagnostics', value: '38 in 2025 YTD' },
      { indicator: 'CMS reimbursement codes added', value: '6 new codes 2025' },
      { indicator: 'Hospital system pilot contracts', value: '+180% YoY' },
    ],
    estimated_peak_months: 22,
    related_trends: ['trend-015', 'trend-007'],
    updated_at: '2025-06-14T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-013',
    trend_id: 'trend-013',
    analysis_stage: 'Saturating',
    confidence_percent: 90,
    historical_pattern: 'Classic consumer SaaS saturation. Category established, growth decelerating, consolidation beginning.',
    ai_notes: 'The mental health app market has 500+ players competing for the same users. Differentiation is extremely difficult. Survivors will be those with clinical validation (studies, partnerships) or payor integration.',
    key_indicators: [
      { indicator: 'Total funded mental health startups', value: '600+ globally' },
      { indicator: 'User retention at 6 months', value: '18% average (declining)' },
      { indicator: 'Payor reimbursement deals', value: '28 major insurer contracts' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-016', 'trend-015'],
    updated_at: '2025-06-10T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-014',
    trend_id: 'trend-014',
    analysis_stage: 'Emerging',
    confidence_percent: 55,
    historical_pattern: 'Nascent category. No reliable historical comp. Consumer interest outpacing scientific consensus.',
    ai_notes: 'Longevity tech is a pre-category. Bryan Johnson and similar figures are creating consumer demand that is outpacing the science. The near-term opportunity is biomarker tracking and personalized supplement stacks, not lifespan extension. Low confidence due to regulatory and scientific uncertainty.',
    key_indicators: [
      { indicator: 'Longevity clinic openings (2025)', value: '42 in US/EU' },
      { indicator: 'Epigenetic test kit sales', value: '+340% YoY' },
      { indicator: 'VC funding in longevity', value: '$1.8B in 2025' },
    ],
    estimated_peak_months: 48,
    related_trends: ['trend-015', 'trend-043'],
    updated_at: '2025-06-09T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-015',
    trend_id: 'trend-015',
    analysis_stage: 'Peaking',
    confidence_percent: 86,
    historical_pattern: 'Medicare reimbursement tail is sustaining growth past typical innovation curve.',
    ai_notes: 'RPM billing codes created a gold rush. Saturation is coming as CMS tightens compliance requirements. Companies with clinical workflow integration (not just hardware) will survive the upcoming reimbursement tightening.',
    key_indicators: [
      { indicator: 'RPM billing claims volume', value: '+280% YoY' },
      { indicator: 'Medicare RPM reimbursement spend', value: '$4.2B in 2025' },
      { indicator: 'New RPM vendor launches', value: '12 in 2025 YTD' },
    ],
    estimated_peak_months: 6,
    related_trends: ['trend-012', 'trend-013'],
    updated_at: '2025-06-13T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-016',
    trend_id: 'trend-016',
    analysis_stage: 'Accelerating',
    confidence_percent: 84,
    historical_pattern: 'EdTech has seen multiple hype cycles; this iteration is fundamentally different due to LLM conversational ability.',
    ai_notes: 'AI tutoring has achieved 2-sigma improvement over classroom instruction in controlled studies. Adoption is gated by school procurement cycles (18-24 months) and union resistance. Consumer direct-to-student is the faster path.',
    key_indicators: [
      { indicator: 'Student learning outcome improvement', value: '2.1 sigma vs control' },
      { indicator: 'K-12 district pilots', value: '400+ districts enrolled' },
      { indicator: 'Consumer tutor app revenue', value: '+220% YoY' },
    ],
    estimated_peak_months: 24,
    related_trends: ['trend-001', 'trend-017'],
    updated_at: '2025-06-14T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-017',
    trend_id: 'trend-017',
    analysis_stage: 'Emerging',
    confidence_percent: 70,
    historical_pattern: 'Badge credentialing failed once before (Mozilla Open Badges). New cycle has employer buy-in that previous attempts lacked.',
    ai_notes: 'Micro-credentials are gaining employer acceptance faster than expected. LinkedIn and Workday integrations are the unlock. The failure mode is credential inflation -- if everyone has 50 badges, they mean nothing.',
    key_indicators: [
      { indicator: 'Employer acceptance programs', value: '180 Fortune 1000 signatories' },
      { indicator: 'Credential issuance growth', value: '+156% YoY' },
      { indicator: 'Platform revenue per credential', value: '$12-18 average' },
    ],
    estimated_peak_months: 32,
    related_trends: ['trend-016', 'trend-039'],
    updated_at: '2025-06-07T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-018',
    trend_id: 'trend-018',
    analysis_stage: 'Saturating',
    confidence_percent: 87,
    historical_pattern: 'Post-pandemic EdTech bubble deflating. Bootcamp outcomes under scrutiny.',
    ai_notes: 'Traditional coding bootcamps face twin pressures: AI code generation reducing demand for entry-level developers, and ISA regulatory crackdowns. The pivot is into enterprise upskilling and domain-specific tech training.',
    key_indicators: [
      { indicator: 'Bootcamp enrollment YoY', value: '-22% from peak' },
      { indicator: 'Placement rate at top 10 bootcamps', value: '61% (down from 84%)' },
      { indicator: 'Enterprise upskilling contract growth', value: '+45% offsetting decline' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-016', 'trend-006'],
    updated_at: '2025-06-01T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-019',
    trend_id: 'trend-019',
    analysis_stage: 'Peaking',
    confidence_percent: 82,
    historical_pattern: 'Newsletter tools followed the pod platform playbook: fragmentation then rapid consolidation.',
    ai_notes: 'The newsletter tool category is consolidating. Two or three platforms will win. Differentiation is shifting from distribution to analytics and monetization primitives. Building yet another newsletter tool is very high risk.',
    key_indicators: [
      { indicator: 'Newsletter creator economy revenue', value: '$2.8B in 2025' },
      { indicator: 'New newsletter tool launches', value: 'Declined 35% from peak' },
      { indicator: 'Top 3 platforms market share', value: '71% (consolidating)' },
    ],
    estimated_peak_months: 4,
    related_trends: ['trend-020', 'trend-022'],
    updated_at: '2025-06-15T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-020',
    trend_id: 'trend-020',
    analysis_stage: 'Saturating',
    confidence_percent: 91,
    historical_pattern: 'Classic consumer social monetization curve. Platforms max out ad CPMs, seek new revenue streams.',
    ai_notes: 'Short-form video monetization is mature. The innovation window has closed for pure-play tools. The next cycle is integration -- combining short-form video production with commerce, subscriptions, and community in one stack.',
    key_indicators: [
      { indicator: 'Avg creator revenue per 1M views', value: 'Flat for 8 quarters' },
      { indicator: 'Merch + sub revenue share', value: '38% of creator total (up from 12%)' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-027', 'trend-019'],
    updated_at: '2025-06-10T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-021',
    trend_id: 'trend-021',
    analysis_stage: 'Emerging',
    confidence_percent: 68,
    historical_pattern: 'Brand management tools have a slow but steady adoption curve in agency and enterprise segments.',
    ai_notes: 'AI brand voice is solving a real pain point: maintaining consistency across dozens of AI-generated content pieces. The TAM is every company using AI to write content (nearly all). Pricing will be anchored to existing brand management tools.',
    key_indicators: [
      { indicator: 'Brands with AI content policies', value: '78% of Fortune 500' },
      { indicator: 'Brand voice API integrations', value: '340 SaaS tools integrated' },
    ],
    estimated_peak_months: 28,
    related_trends: ['trend-006', 'trend-019'],
    updated_at: '2025-06-12T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-022',
    trend_id: 'trend-022',
    analysis_stage: 'Accelerating',
    confidence_percent: 77,
    historical_pattern: 'Audio editing tools followed a clear adoption curve. Podcast production AI is 2 years into that same arc.',
    ai_notes: 'Podcast production AI has achieved strong product-market fit with solo creators. The enterprise segment (media companies) is 12-18 months behind. Revenue per user is higher in enterprise but sales cycle is long.',
    key_indicators: [
      { indicator: 'AI editing tools adoption among podcasters', value: '42% of active shows' },
      { indicator: 'Time saved per episode', value: '4.2 hours average' },
      { indicator: 'Media company pilots', value: '28 announced' },
    ],
    estimated_peak_months: 18,
    related_trends: ['trend-004', 'trend-019'],
    updated_at: '2025-06-13T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-023',
    trend_id: 'trend-023',
    analysis_stage: 'Emerging',
    confidence_percent: 73,
    historical_pattern: 'Niche language adoption curves are long. Go took 8 years to mainstream. Rust is on year 6.',
    ai_notes: 'Rust for web is technically compelling but faces a steep developer experience gradient. The WebAssembly runtime improvements in 2025 have cut the performance-adoption gap significantly. Best opportunity: performance-critical browser applications (collaborative editing, video processing, games).',
    key_indicators: [
      { indicator: 'Rust WASM crate downloads', value: '+280% YoY' },
      { indicator: 'Rust in top 5 "most loved" languages', value: '9 consecutive years' },
      { indicator: 'Production WASM deployments', value: '1,200+ tracked sites' },
    ],
    estimated_peak_months: 36,
    related_trends: ['trend-035', 'trend-026'],
    updated_at: '2025-06-11T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-024',
    trend_id: 'trend-024',
    analysis_stage: 'Saturating',
    confidence_percent: 90,
    historical_pattern: 'CMS market has been consolidating since 2019. Headless has won structurally but the market is mature.',
    ai_notes: 'Headless CMS is a solved problem at the infrastructure level. The remaining differentiation is developer experience, AI content tooling, and commerce integrations. New entrants face extreme competition from Contentful, Sanity, Strapi.',
    key_indicators: [
      { indicator: 'Market share of top 5 headless CMS', value: '76% (stable)' },
      { indicator: 'New entrant funding YoY', value: '-55%' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-035', 'trend-041'],
    updated_at: '2025-05-20T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-025',
    trend_id: 'trend-025',
    analysis_stage: 'Emerging',
    confidence_percent: 74,
    historical_pattern: 'Mirrors APM (application performance monitoring) adoption 2012-2016. LLM observability is earlier on that curve.',
    ai_notes: 'LLM observability is a green field market. Every company building with LLMs needs prompt tracing, cost monitoring, and quality evaluation. The TAM grows with AI adoption. First-mover advantage is high because observability data creates compounding benchmarks.',
    key_indicators: [
      { indicator: 'AI observability tool installs', value: '+420% YoY' },
      { indicator: 'Avg monthly spend per engineering team', value: '$340' },
      { indicator: 'Integration partners', value: '65 LLM providers supported' },
    ],
    estimated_peak_months: 28,
    related_trends: ['trend-001', 'trend-006', 'trend-039'],
    updated_at: '2025-06-14T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-026',
    trend_id: 'trend-026',
    analysis_stage: 'Peaking',
    confidence_percent: 88,
    historical_pattern: 'Classic B2B SaaS peak. Category recognized, enterprise deals signed, growth-to-profitability shift underway.',
    ai_notes: 'Feature flag platforms are a necessary piece of the modern dev stack. The market will consolidate into 2-3 leaders. The edge case to watch is AI-powered experimentation layered on top of feature flags -- that is the next value-add.',
    key_indicators: [
      { indicator: 'Fortune 500 feature flag adoption', value: '84%' },
      { indicator: 'Market concentration (top 3)', value: '68% share' },
      { indicator: 'Average deal size growth', value: '+12% YoY (slowing)' },
    ],
    estimated_peak_months: 6,
    related_trends: ['trend-039', 'trend-025'],
    updated_at: '2025-06-10T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-027',
    trend_id: 'trend-027',
    analysis_stage: 'Accelerating',
    confidence_percent: 81,
    historical_pattern: 'TikTok Shop proved the model in Asia 3 years before Western adoption. Playbook is confirmed.',
    ai_notes: 'Social commerce is poised to reach $1T GMV by 2028 in the US/EU. The infrastructure play (integrations, analytics, fulfillment) is earlier stage than the consumer app layer. B2B tools for brands managing social commerce operations are the highest-margin opportunity.',
    key_indicators: [
      { indicator: 'TikTok Shop GMV growth', value: '+340% YoY' },
      { indicator: 'Brand social commerce adoption', value: '62% of top 1000 brands' },
      { indicator: 'Social commerce tool funding', value: '$890M in 2025' },
    ],
    estimated_peak_months: 20,
    related_trends: ['trend-029', 'trend-020'],
    updated_at: '2025-06-13T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-028',
    trend_id: 'trend-028',
    analysis_stage: 'Emerging',
    confidence_percent: 66,
    historical_pattern: 'Resale/circular economy has had multiple false starts. Current signal is stronger due to brand participation.',
    ai_notes: 'Recommerce is finally getting brand buy-in (Patagonia, Lululemon, REI). The infrastructure play -- building the white-label trade-in and resale platform for brands -- has strong unit economics. Certification and grading logistics remain the hard part.',
    key_indicators: [
      { indicator: 'Brand-run resale programs launched', value: '140 in 2025 YTD' },
      { indicator: 'Recommerce market size', value: '$48B and growing 15% YoY' },
    ],
    estimated_peak_months: 34,
    related_trends: ['trend-043', 'trend-027'],
    updated_at: '2025-06-09T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-029',
    trend_id: 'trend-029',
    analysis_stage: 'Accelerating',
    confidence_percent: 79,
    historical_pattern: 'AI creative tools follow the "10x cheaper, good enough" adoption pattern seen with stock photo disruption.',
    ai_notes: 'AI product photography has crossed the quality threshold for most e-commerce use cases. The SMB market is the beachhead -- studio photography is unaffordable for most sellers. Enterprise adoption will lag 12-18 months due to brand control concerns.',
    key_indicators: [
      { indicator: 'Cost per product image (AI vs studio)', value: '$0.12 vs $85' },
      { indicator: 'E-commerce platform integrations', value: '28 native integrations' },
      { indicator: 'Seller adoption rate on Shopify', value: '18% of stores with 100+ SKUs' },
    ],
    estimated_peak_months: 16,
    related_trends: ['trend-004', 'trend-027'],
    updated_at: '2025-06-14T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-030',
    trend_id: 'trend-030',
    analysis_stage: 'Declining',
    confidence_percent: 89,
    historical_pattern: 'Post-COVID reversal. Subscription box category grew 400% during lockdowns; now facing churn headwinds.',
    ai_notes: 'The subscription box model is in structural decline. Consumer fatigue, shipping cost inflation, and subscription management apps (allowing easy cancellation) are compounding. The model only works at extreme niche specificity (professional tools, regulated products).',
    key_indicators: [
      { indicator: 'Subscription box cancellation rate', value: '44% annually (up from 28%)' },
      { indicator: 'New box launches YoY', value: '-60% from 2021 peak' },
      { indicator: 'Average LTV per subscriber', value: '-32% over 3 years' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-027', 'trend-020'],
    updated_at: '2025-06-01T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-031',
    trend_id: 'trend-031',
    analysis_stage: 'Saturating',
    confidence_percent: 78,
    historical_pattern: 'DeFi follows crypto market cycles. Current cycle has longer institutional participation tail.',
    ai_notes: 'DeFi 2.0 improved capital efficiency significantly but has not solved the adoption problem. Non-crypto native users still find onboarding too complex. Real-world asset tokenization bridging into DeFi is the most compelling near-term use case.',
    key_indicators: [
      { indicator: 'Total Value Locked (TVL) growth', value: '+8% MoM (slowing)' },
      { indicator: 'Institutional DeFi wallets', value: '2,400 tracked addresses' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-034', 'trend-033'],
    updated_at: '2025-06-08T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-032',
    trend_id: 'trend-032',
    analysis_stage: 'Declining',
    confidence_percent: 82,
    historical_pattern: 'Play-to-earn model was exposed as unsustainable. Classic asset pyramid collapse.',
    ai_notes: 'Web3 gaming\'s core mechanic (play-to-earn) proved mathematically unsustainable. The remaining signal is in digital ownership of in-game assets without speculative earn mechanics. A few studios are building this correctly but the category label is toxic.',
    key_indicators: [
      { indicator: 'P2E game active users', value: '-78% from 2022 peak' },
      { indicator: 'Web3 game studio closures', value: '34 in 2025 YTD' },
      { indicator: 'NFT gaming transaction volume', value: '-91% from peak' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-031', 'trend-033'],
    updated_at: '2025-05-01T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-033',
    trend_id: 'trend-033',
    analysis_stage: 'Emerging',
    confidence_percent: 63,
    historical_pattern: 'Early primitives stage. Comparable to OAuth adoption curve before social login became standard.',
    ai_notes: 'Account abstraction removes the most significant UX barrier in crypto. Without seed phrases, mainstream adoption becomes feasible. The technical challenge is gas sponsorship economics. Best opportunity: wallets targeted at specific use cases (gaming, DeFi, enterprise).',
    key_indicators: [
      { indicator: 'ERC-4337 smart accounts deployed', value: '8.4M wallets' },
      { indicator: 'Gasless transaction volume', value: '+380% QoQ' },
    ],
    estimated_peak_months: 38,
    related_trends: ['trend-034', 'trend-031'],
    updated_at: '2025-06-11T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-034',
    trend_id: 'trend-034',
    analysis_stage: 'Emerging',
    confidence_percent: 70,
    historical_pattern: 'Securities tokenization has a 10-year history of false starts. Regulatory clarity in 2024-2025 is the difference.',
    ai_notes: 'RWA tokenization is gaining real traction with BlackRock and Franklin Templeton as signal validators. The opportunity is plumbing for secondary market trading and compliance -- the assets themselves will be tokenized by incumbents, but the infrastructure needs building.',
    key_indicators: [
      { indicator: 'Tokenized RWA total value', value: '$14B (up from $2B in 2023)' },
      { indicator: 'SEC guidance clarity events', value: '3 major rulings in 2025' },
      { indicator: 'Institutional RWA protocol launches', value: '22 announced' },
    ],
    estimated_peak_months: 30,
    related_trends: ['trend-031', 'trend-033'],
    updated_at: '2025-06-13T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-035',
    trend_id: 'trend-035',
    analysis_stage: 'Accelerating',
    confidence_percent: 85,
    historical_pattern: 'CDN adoption 2005-2012 is the historical analog. Edge compute is following the same diffusion path.',
    ai_notes: 'Edge compute is becoming the default for latency-sensitive applications. The developer experience gap vs. traditional cloud is closing rapidly. Key moat is network density -- the more PoPs, the more valuable the network.',
    key_indicators: [
      { indicator: 'Edge function invocations growth', value: '+320% YoY' },
      { indicator: 'Enterprise edge contracts', value: '+145% YoY' },
      { indicator: 'Average latency improvement', value: '68ms to 12ms (P95)' },
    ],
    estimated_peak_months: 22,
    related_trends: ['trend-005', 'trend-038'],
    updated_at: '2025-06-15T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-036',
    trend_id: 'trend-036',
    analysis_stage: 'Peaking',
    confidence_percent: 92,
    historical_pattern: 'GPU cloud is peaking due to hyperscaler capacity additions outpacing demand growth for first time.',
    ai_notes: 'The GPU cloud gold rush is ending. AWS, Google, and Azure are all deploying massive capacity in 2025-2026. Spot prices are declining 40% annually. The moat shifts from GPU access to software stack, developer experience, and specialized chips (TPUs, custom ASICs).',
    key_indicators: [
      { indicator: 'H100 spot price change YoY', value: '-42%' },
      { indicator: 'Hyperscaler GPU capacity additions', value: '+280% in 2025' },
      { indicator: 'Specialized AI cloud churn rate', value: '+18% as prices fall' },
    ],
    estimated_peak_months: 2,
    related_trends: ['trend-001', 'trend-035'],
    updated_at: '2025-06-15T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-037',
    trend_id: 'trend-037',
    analysis_stage: 'Saturating',
    confidence_percent: 88,
    historical_pattern: 'FinOps followed a textbook B2B SaaS maturity curve. Category is now in late growth / early saturation.',
    ai_notes: 'FinOps platforms have commoditized. The remaining differentiation is AI-powered anomaly detection and automated remediation. Pure cost visibility tools are commoditized. The next play is FinOps + AI cost attribution (ML training run costs, inference cost tracking).',
    key_indicators: [
      { indicator: 'FinOps tool market penetration (>500 seat cos)', value: '71%' },
      { indicator: 'Average cloud savings rate', value: '23% (benchmark stabilizing)' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-036', 'trend-039'],
    updated_at: '2025-06-05T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-038',
    trend_id: 'trend-038',
    analysis_stage: 'Accelerating',
    confidence_percent: 81,
    historical_pattern: 'Serverless compute pattern is now repeating in the database layer on a 5-year lag.',
    ai_notes: 'Serverless databases solve the cold start and connection pooling problems that plagued early attempts. Neon and PlanetScale have proven the model. The next phase is distributed serverless OLAP for analytics workloads.',
    key_indicators: [
      { indicator: 'Serverless DB managed instances', value: '+180% YoY' },
      { indicator: 'Cold start latency improvement', value: '400ms to 14ms avg' },
      { indicator: 'Developer survey preference', value: '38% prefer serverless vs 12% in 2022' },
    ],
    estimated_peak_months: 20,
    related_trends: ['trend-035', 'trend-025'],
    updated_at: '2025-06-14T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-039',
    trend_id: 'trend-039',
    analysis_stage: 'Accelerating',
    confidence_percent: 87,
    historical_pattern: 'Enterprise software AI integration mirrors SaaS adoption 2010-2015. Long sales cycles but sticky revenue.',
    ai_notes: 'Enterprise AI copilots have the clearest ROI story in AI: measurable productivity gains in white-collar workflows. Microsoft Copilot has validated demand. The opportunity is in vertical-specific copilots with deeper workflow integration than generic tools.',
    key_indicators: [
      { indicator: 'Enterprise AI productivity tool spend', value: '$18B in 2025' },
      { indicator: 'ROI studies published', value: '180 peer-reviewed or major firm' },
      { indicator: 'Average productivity gain cited', value: '32% for routine tasks' },
    ],
    estimated_peak_months: 18,
    related_trends: ['trend-001', 'trend-040', 'trend-041'],
    updated_at: '2025-06-15T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-040',
    trend_id: 'trend-040',
    analysis_stage: 'Peaking',
    confidence_percent: 89,
    historical_pattern: 'Horizontal SaaS peaked 2015-2018 and vertical SaaS is on a similar arc, slightly delayed.',
    ai_notes: 'Vertical SaaS continues to generate outsized returns (3-5x revenue multiples vs horizontal tools). The remaining white space is in "unsexy" industries -- pest control, funeral homes, marina management. These have low digital penetration and high switching costs once adopted.',
    key_indicators: [
      { indicator: 'Vertical SaaS M&A deals YoY', value: '+28%' },
      { indicator: 'Average ARR multiple paid', value: '8.2x (premium to horizontal)' },
      { indicator: 'NPS advantage vs horizontal tools', value: '+36 points' },
    ],
    estimated_peak_months: 10,
    related_trends: ['trend-008', 'trend-039'],
    updated_at: '2025-06-12T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-041',
    trend_id: 'trend-041',
    analysis_stage: 'Saturating',
    confidence_percent: 92,
    historical_pattern: 'Workflow automation category fully mature. RPA wave pre-dated this; no-code wave 2022 was the peak.',
    ai_notes: 'Low-code workflow automation is saturated at the IT buyer level. The next wave is adding AI inference into workflows (not just logic routing). Platforms that add native LLM steps to workflows will extend their lifecycle significantly.',
    key_indicators: [
      { indicator: 'Market leader (Zapier/Make) revenue growth', value: '+6% YoY (slowing)' },
      { indicator: 'New workflow tool launches', value: 'Declining 25% YoY' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-001', 'trend-039'],
    updated_at: '2025-06-10T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-042',
    trend_id: 'trend-042',
    analysis_stage: 'Emerging',
    confidence_percent: 57,
    historical_pattern: 'Usage-based pricing went through this same adoption arc 2017-2021. Outcome-based is one step further.',
    ai_notes: 'Outcome-based contracting is a pricing model innovation, not a product category. It requires deep measurement infrastructure and customer trust. Best candidates: AI tools where outcomes are measurable (sales outreach, legal research, code generation).',
    key_indicators: [
      { indicator: 'B2B SaaS companies piloting OBC', value: '42 public announcements' },
      { indicator: 'Average contract size increase vs seat model', value: '+85%' },
    ],
    estimated_peak_months: 45,
    related_trends: ['trend-039', 'trend-040'],
    updated_at: '2025-06-10T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-043',
    trend_id: 'trend-043',
    analysis_stage: 'Emerging',
    confidence_percent: 65,
    historical_pattern: 'Regulatory-driven market. ESG reporting mandates are the demand catalyst.',
    ai_notes: 'Climate tech data is gated on regulatory mandates. SEC climate disclosure rules and EU CSRD are forcing large companies to invest. The immediate opportunity is compliance tooling -- building the accounting and audit trail. Longer-term value is risk analytics.',
    key_indicators: [
      { indicator: 'CSRD-mandated companies (EU)', value: '50,000 companies in scope' },
      { indicator: 'ESG data vendor funding 2025', value: '$2.1B' },
      { indicator: 'Average enterprise climate budget', value: '$420K (up 180%)' },
    ],
    estimated_peak_months: 30,
    related_trends: ['trend-044', 'trend-037'],
    updated_at: '2025-06-11T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-044',
    trend_id: 'trend-044',
    analysis_stage: 'Emerging',
    confidence_percent: 48,
    historical_pattern: 'No reliable historical comp. Defense/aerospace software is the closest analog.',
    ai_notes: 'Space economy software is genuinely early. SpaceX and launch incumbents handle their own software. The commercial opportunity is for companies providing services to small satellite operators (1,200+ in orbit by 2025). Niche but high ACV potential.',
    key_indicators: [
      { indicator: 'Commercial satellite launches', value: '420 in 2025 YTD' },
      { indicator: 'Small satellite operator count', value: '380 companies globally' },
    ],
    estimated_peak_months: 60,
    related_trends: ['trend-043', 'trend-035'],
    updated_at: '2025-06-08T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
  {
    id: 'analysis-045',
    trend_id: 'trend-045',
    analysis_stage: 'Declining',
    confidence_percent: 75,
    historical_pattern: 'Hype cycle overshoot followed by realistic timeline reset. Autonomous vehicle timeline has been pushed 10 years.',
    ai_notes: 'Level 4+ autonomy has been pushed back substantially. Fleet management software for existing semi-autonomous vehicles (L2/L3) has steady but slow-growing demand. Full autonomy software will require a new catalyst (regulatory, technical breakthrough) to re-accelerate.',
    key_indicators: [
      { indicator: 'Robotaxi operational miles growth', value: '+12% YoY (far below projections)' },
      { indicator: 'AV startup funding decline', value: '-68% from 2021 peak' },
    ],
    estimated_peak_months: 0,
    related_trends: ['trend-005', 'trend-043'],
    updated_at: '2025-05-15T00:00:00Z',
    analyzed_by: 'gpt-4o-analysis-v2',
  },
]
