import type { Watchlist } from '../types'

export const mockWatchlists: readonly Watchlist[] = [
  {
    id: 'watchlist-001',
    user_id: 'user-mock-001',
    name: 'High-Conviction AI Opportunities',
    description: 'AI/ML trends with low competition and strong early signals. Focus on infrastructure and tooling plays.',
    keyword_filters: ['AI', 'LLM', 'agents', 'inference', 'synthetic'],
    category_filters: ['AI/ML', 'Dev Tools'],
    min_trend_score: 25,
    created_at: '2025-04-01T00:00:00Z',
    updated_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'watchlist-002',
    user_id: 'user-mock-001',
    name: 'Emerging Dev Tools',
    description: 'Developer tooling trends under the radar. Picks-and-shovels plays with enterprise pull.',
    keyword_filters: ['observability', 'edge', 'serverless', 'WASM', 'Rust'],
    category_filters: ['Dev Tools', 'Infrastructure'],
    min_trend_score: 20,
    created_at: '2025-04-15T00:00:00Z',
    updated_at: '2025-06-14T00:00:00Z',
  },
  {
    id: 'watchlist-003',
    user_id: 'user-mock-001',
    name: 'EdTech & Creator Economy',
    description: 'Education technology and creator tools with proven monetization signals.',
    keyword_filters: ['education', 'tutoring', 'creator', 'newsletter', 'podcast'],
    category_filters: ['Education', 'Creator Tools'],
    min_trend_score: 40,
    created_at: '2025-05-01T00:00:00Z',
    updated_at: '2025-06-12T00:00:00Z',
  },
  {
    id: 'watchlist-004',
    user_id: 'user-mock-001',
    name: 'Vertical SaaS Pipeline',
    description: 'Enterprise and vertical SaaS plays with strong monetization and medium competition. Target M&A candidates.',
    keyword_filters: ['vertical', 'SaaS', 'enterprise', 'embedded', 'neobank'],
    category_filters: ['Enterprise', 'Fintech', 'E-Commerce'],
    min_trend_score: 50,
    created_at: '2025-05-10T00:00:00Z',
    updated_at: '2025-06-10T00:00:00Z',
  },
]
